auth:
    username: your-bmw-email-address
    password: your-bmw-password
monitor:
    interval: 60
    reservation_url: https://driving-center.bmw.co.kr/orders/programs/products/view
    program_list_url: https://driving-center.bmw.co.kr/useAmount/view
programs:
    - name: Starter Pack
      keywords:
        - Starter Pack
        - 스타터 팩
      isopen: false
      lastchecked: 0001-01-01T00:00:00Z
    - name: M Drift II
      keywords:
        - M Drift II
        - M 드리프트 II
      isopen: false
      lastchecked: 0001-01-01T00:00:00Z
    - name: M Drift I
      keywords:
        - M Drift I
        - M 드리프트 I
      isopen: false
      lastchecked: 0001-01-01T00:00:00Z
    - name: Owners Drift Day
      keywords:
        - Owners Drift Day
        - 오너스 드리프트 데이
      isopen: false
      lastchecked: 0001-01-01T00:00:00Z
    - name: M Intensive
      keywords:
        - M Intensive
        - M 인텐시브
      isopen: false
      lastchecked: 0001-01-01T00:00:00Z
    - name: M Core
      keywords:
        - M Core
        - M 코어
      isopen: false
      lastchecked: 0001-01-01T00:00:00Z
    - name: Owners Track Day
      keywords:
        - Owners Track Day
        - 오너스 트랙 데이
      isopen: false
      lastchecked: 0001-01-01T00:00:00Z
email:
    smtp:
        host: smtp.gmail.com
        port: 587
        username: your-gmail-address
        password: your-gmail-app-password
    from: your-gmail-address
    to:
        - your-gmail-address
    subject: BMW 드라이빙 센터 예약 오픈 알림 (Reservation Open Alert)
